version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: console
      POSTGRES_PASSWORD: console
      POSTGRES_DB: console
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: console@nais.io
      PGADMIN_DEFAULT_PASSWORD: console
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin: