version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: console
      POSTGRES_PASSWORD: console
      POSTGRES_DB: console
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    depends_on:
      - postgres
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: