apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        kubectl.kubernetes.io/default-container: {{ .Chart.Name }}
        {{- include "console.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "console.name" . }}
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0 # make sure the use the latest version
          command:
            - "/cloud_sql_proxy"
            - "-log_debug_stdout"
            - "-instances={{ .Values.envProjectId }}:europe-north1:{{ .Values.database.instance }}=tcp:5432"
            - "-enable_iam_login"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.22"
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONSOLE_LISTEN_ADDRESS
              value: 0.0.0.0:3000
            - name: CONSOLE_DATABASE_URL
              value: "postgres://console@{{ .Values.envProjectId }}.iam@127.0.0.1:5432/console?sslmode=disable"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
