{{- if .Values.ingress.enabled -}}
{{- $fullName := include "console.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            pathType: ImplementationSpecific
          - path: /query
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            pathType: ImplementationSpecific
    {{- end }}
  {{- end }}
