apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console.name" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: console@{{ .Values.envProjectId }}.iam.gserviceaccount.com