apiVersion: v1
kind: Secret
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
stringData:
  CONSOLE_DATABASE_URL: {{ .Values.database.url }}
