envProjectId: ""
database:
  url: ""
image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/console
  pullPolicy: IfNotPresent
  tag: main

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nais-ingress
  hosts: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
